### ISSUE TITLE
Find a way to remove this.userId and prevent restarting the publication when userId changes

### ISSUE THREAD

**Issue by mitar** [peerlibrary/meteor-reactive-publish#1]
It would be great to find a way to remove `this.userId` and prevent the publication to be restarted by Meteor when `userId` or other connection data changes. And expose those as reactive data sources inside the publish one can use inside the `autorun`. That might be much better for performance and address issues associated with restarting the publication.

**Comment by steph643** [comment]
For reference, here is the kind of issue associated with the automatic publication restart: https://github.com/meteor/meteor/issues/4705

**Comment by mitar** [comment]
This is especially interesting now with the [subscription data](https://github.com/peerlibrary/meteor-subscription-data) package. `userId` could be just something inside the subscription's reactive data context. So if one wants to depend on `userId`, it registers reactivity, otherwise not.

**Comment by mitar** [comment]
I opened: https://github.com/meteor/meteor/issues/6441

**Comment by mitar** [comment]
After more thought. I think this is premature optimization. I think sharing subscriptions between logged in and not logged in users is not as common. And publish functions should anyway be very lightweight, mostly just doing ACL and copying data from one source to output. So rerunning should not be very costly, probably as costly as running ACLs again anyway.
