### ISSUE TITLE
Performance notes?

### ISSUE THREAD

**Issue by lsunsi** [peerlibrary/meteor-reactive-publish#10]
How does well this package perform compared to publish-composite?
Seems to be pretty heavy on the server.

**Comment by dpatte** [comment]
In my case I cannot use publish composite, as it doesn't provide the features I need.

**Comment by mitar** [comment]
> Seems to be pretty heavy on the server.

Based on what are you determining this? Have you made any comparisons/benchmarks.

Because I think it is the same. All those packages use the same underlying idea, just this one generalizes it to full reactivity.

**Comment by mitar** [comment]
So, please, instead of speculation, show numbers. :-) Make an example and test it out, then we will all have more information.
