### ISSUE TITLE
Issue when using idGeneration: 'MONGO'

### ISSUE THREAD

**Issue by dpatte** [peerlibrary/meteor-reactive-publish#12]
While using this module I sometimes get the following error

```
Exception in defer callback: Error: Future resolved more than once
I20160114-15:20:42.939(-5)?     at Object.Future.return (/home/dpatte/.meteor/packages/meteor-tool/.1.1.10.6elsyt++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:226:10)
I20160114-15:20:42.939(-5)?     at TrackerInstance._runFlush (packages/peerlibrary_server-autorun/packages/peerlibrary_server-autorun.js:186:1)
I20160114-15:20:42.939(-5)?     at packages/peerlibrary_server-autorun/packages/peerlibrary_server-autorun.js:104:1
I20160114-15:20:42.939(-5)?     at packages/peerlibrary_server-autorun/packages/peerlibrary_server-autorun.js:90:1
I20160114-15:20:42.939(-5)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160114-15:20:42.939(-5)?     at packages/meteor/timers.js:6:1
I20160114-15:20:42.939(-5)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
```

I am using calls to Meteor.user().find and .findOne in my publish function. Could this be an issue?

**Comment by mitar** [comment]
Please create a reproduction. I do not get such errors and I cannot really help much without something to work here.

One thing to have in mind here is that such errors can occur when there are some other error conditions happening. So because things are asynchronous one side can fail, resolve the future as failure, while something else keeps running and tries to resolve it later again.

> I am using calls to Meteor.user().find and .findOne in my publish function. Could this be an issue?

It shouldn't be, but maybe it is. Please make a reproduction.

**Comment by mitar** [comment]
Ping?

**Comment by mitar** [comment]
Ping?

**Comment by dpatte** [comment]
Sorry for the delay, but I have switched to Reywood:Publish-Composite now, which seems to handle my use case better for me.

**Comment by mzygmunt** [comment]
I've the same issue. 

`Exception in defer callback: Error: Future resolved more than once` 
`I20160313-23:24:54.901(1)?     at Object.Future.return (/Users/mzygmunt/.meteor/packages/meteor-tool/.1.1.11-faster-rebuild.0.d7n8jc++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:226:10)`
`I20160313-23:24:54.901(1)?     at TrackerInstance._runFlush (packages/peerlibrary_server-autorun/packages/peerlibrary_server-autorun.js:186:1)`
`I20160313-23:24:54.901(1)?     at packages/peerlibrary_server-autorun/packages/peerlibrary_server-autorun.js:104:1`
`I20160313-23:24:54.901(1)?     at packages/peerlibrary_server-autorun/packages/peerlibrary_server-autorun.js:90:1`
`I20160313-23:24:54.902(1)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)`
`I20160313-23:24:54.902(1)?     at packages/meteor/timers.js:6:1`
`I20160313-23:24:54.902(1)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)`

Here is my source of publish func:

``` javascript
Meteor.publish('test', function () {
    this.autorun(function (computation) {
        let token = self._token.get(); //get token string
        let objID = new Meteor.Collection.ObjectID((token));
        return Sessions.find({_id: objID});
    })
});
```

**Comment by mitar** [comment]
Can you create a reproduction?

**Comment by mzygmunt** [comment]
test.js

``` javascript
Books = new Mongo.Collection('books', {idGeneration: 'MONGO'});

if (Meteor.isClient) {
    Meteor.subscribe('books');

    Template.test.helpers({
        books: function () {
            return Books.find();
        }
    });

    Template.test.events({
        'click #showComedies': function () {
            Meteor.call('showComedies');
        },
        'click #showHorrors': function () {
            Meteor.call('showHorrors');
        }
    });
}

if (Meteor.isServer) {
    let cat = new ReactiveVar('comedy');

    Meteor.methods({
        showComedies: function () {
            cat.set('comedy');
        },
        showHorrors: function () {
            cat.set('horror');
        }
    });

    Meteor.publish('books', function () {
        this.autorun(function (computation) {
            return Books.find({cat: cat.get()});
        });
    });

    Meteor.startup(function () {
        Books.remove({});
        Books.insert({title: 'Book 1', cat: 'comedy'});
        Books.insert({title: 'Book 2', cat: 'comedy'});
        Books.insert({title: 'Book 3', cat: 'horror'});
        Books.insert({title: 'Book 4', cat: 'comedy'});
        Books.insert({title: 'Book 5', cat: 'horror'});
    });
}
```

``` html
<head>
    <title>test</title>
</head>

<body>
{{> test}}
</body>

<template name="test">
    <button id="showComedies">Show comedies</button>
    <button id="showHorrors">Show horrors</button>
    <ul>{{#each books}}
        <li>{{title}}</li>
    {{/each}}</ul>
</template>
```

And please click "Show horrors".

It seems {idGeneration: 'MONGO'} and default MongoID causes problem. With default Meteor's ids all works fine.

**Comment by mitar** [comment]
Sorry, by reproduction I meant a repository I can clone and run. See [documentation here](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-a-bug-in-meteor). In this way it will really simplify the amount of work I have to do, but I do understand that it requires a bit more work on your side.

**Comment by mzygmunt** [comment]
Here you are.

https://github.com/mzygmunt/reactive-publish-bug.git

**Comment by mitar** [comment]
Hm, how often does it happens? I cannot reproduce it.

**Comment by mitar** [comment]
Can anyone else reproduce it?

**Comment by dpatte** [comment]
This is what I saw as well.

**Comment by mitar** [comment]
@dpatte: Can you elaborate a bit? Do you see with this repository an error or not when you click the button? Every time?

Which operating system are you using? Are you just running `meteor` or some other version of Meteor?

**Comment by dpatte** [comment]
I opened this ticket, actually, and haven't tried the new repo provided, but while I was using your module I was seeing the same errors from your module as @mzygmunt is now reporting. They occurred whenever a publish occurred. I was running Meteor on Ubuntu 12.04, in a dev environment.

**Comment by mitar** [comment]
Yes, my question is about the reproduction. We want to get a clean reproduction and understand why this is happening to you, while it is not happening to others (or me).

**Comment by dpatte** [comment]
If I have a chance, I'll try the repo, but until then, I may be able to help based on what I remember, if you have any other questions.

**Comment by mzygmunt** [comment]
@mitar I updated the repo. Please check it again.

https://github.com/mzygmunt/reactive-publish-bug.git

**Comment by mitar** [comment]
Perfect. I can reproduce this.

**Comment by mzygmunt** [comment]
That's great! When can we expect to solve the problem?

**Comment by mitar** [comment]
Not so sure. I am a bit busy these weeks. But it seems that the problem is that there is no good support for this IDs in reactive-publish package. The future issue is just a side effect when error is being thrown. It hides the real error.

**Comment by MKRazz** [comment]
+1
