### ISSUE TITLE
Getting Fiber/bindEnvironment error in Meteor 1.3 beta 7

### ISSUE THREAD

**Issue by huttonr** [peerlibrary/meteor-reactive-publish#14]
In using peerlibrary:reactive-publish with Meteor 1.3-modules-beta.7 I get the following error when a user requests a webpage:

```
E20160205-10:55:38.281(-8) (webapp_server.js:716) Error running template: Error: Meteor
code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor
libraries with Meteor.bindEnvironment.
```

This occurs regardless of whether or not `this.autorun` is used.

**Comment by mitar** [comment]
Oh, I saw that. I thought it is from some other package. Are you sure it is related to this mine package? This is great help. :-)

Could you figure out why `webapp_server.js` inteacts with publish? Or is it that it interacts with `autorun`? If you add only [autorun](https://github.com/peerlibrary/meteor-server-autorun) package, does it still complain?

(I do not have time at the moment to look into this so any help you can provide would be great.)

**Comment by huttonr** [comment]
I've isolated that this is actually a `server-autorun` problem, not `reactive-publish`.

https://github.com/peerlibrary/meteor-server-autorun/issues/10

**Comment by mitar** [comment]
Thanks!

**Comment by huttonr** [comment]
[Glad I could serve the "last straw" to catalyze this amazing (and hopefully evolution-inspiring) debate...](https://forums.meteor.com/t/how-open-source-meteor-really-is-if-pull-requests-are-not-getting-in/16483/96)

You never know how the pond will ripple.

Well played my friend and I'm glad I served some part (although very minor).

**Comment by mitar** [comment]
:-)
