### ISSUE TITLE
Collection2

### ISSUE THREAD

**Issue by cunneen** [peerlibrary/meteor-reactive-publish#16]
Is there a way of getting this to work with Collection2 ?

I get the following error:

```
Exception from sub JobDetails id odpZRzshfNhQGvCoW { stack: 'TypeError: Object [object Object] has no method \'autorun\'
    at [object Object].Package (packages/job-details/job-details.js:540:1)
    at packages/matb33_collection-hooks/collection-hooks.js:275:1\n 
```

**Comment by mitar** [comment]
Probably you should make sure this package is loaded before Collection2?

There is no particular reason why it would not work.

**Comment by cunneen** [comment]
Why didn't I think of that? :)
Thanks I'll try it. Thanks also for the super speedy response.

**Comment by cunneen** [comment]
Thanks for the suggestion but I get the same error even when this package is loaded first.

**Comment by mitar** [comment]
Can you make simple reproduction?

**Comment by cunneen** [comment]
It seems to work fine with Collection2 on the todos example, so the problem is obviously something else particular to my app. Thanks, I'll let you know if I find the incompatibility.

**Comment by mitar** [comment]
To me it feels like you are maybe not binding `this` correctly somewhere?

**Comment by cunneen** [comment]
Quite possibly. 
I didn't explicitly bind this. It was in the context of a `Meteor.publish` function, just like the ones in the Readme in this repo. It's probable that another package is interfering with the binding (it's a large app).

**Comment by cunneen** [comment]
I think this is likely the problem:

[https://github.com/matb33/meteor-collection-hooks/blob/master/collection-hooks.js#L269]()

``` js
if (Meteor.isServer) {
  var _publish = Meteor.publish;
  Meteor.publish = function (name, func) {
    return _publish.call(this, name, function () {
      // This function is called repeatedly in publications
      var ctx = this, args = arguments;
      return publishUserId.withValue(ctx && ctx.userId, function () {
        return func.apply(ctx, args);
      });
    });
  };

  // Make the above available for packages with hooks that want to determine
  // whether they are running inside a publish function or not.
  CollectionHooks.isWithinPublish = function isWithinPublish() {
    return publishUserId.get() !== undefined;
  };
}
```

**Comment by cunneen** [comment]
Thanks for all your help! It's working now, and your package solves a huge headache for me. 
I needed to:
1. Edit `.meteor/packages` to make this package appear above `matb33:collection-hooks`
2. Bind `this` to `self` as the first step of my `Meteor.publish` 
3. Wrap the publish function in a `this.autorun` as per your docs.

e.g.

``` js
  Meteor.publish('JobDetails', function () {
    var self = this;

    this.autorun(function(computation) {
      if (!self.userId) { // kick them out if they're not logged in
        self.stop();
        return;
      }

      if (Roles.userIsInRole(self.userId, "customer")) {
//.....
```

**Comment by mitar** [comment]
Great!
