### ISSUE TITLE
ReactiveVar is not defined

### ISSUE THREAD

**Issue by DanielDornhardt** [peerlibrary/meteor-reactive-publish#21]
Hi, I was so happy when I saw the code example of this package:

```
var currentTime = new ReactiveVar(new Date().valueOf());

Meteor.setInterval(function () {
  currentTime.set(new Date().valueOf());
}, 1000); // ms
```

etc.

Now when I try to do just that, I always get the error `ReferenceError: ReactiveVar is not defined` in the server console.

The regular meteor reactive-var - package is in the package.js of the project.

The Meteor Version of this project is 1.3.5.1.

Is there something else I need / does this not work anymore?

I'm looking for a way to create regular self-updating publications, eg. check for any documents with a release date earlier than now.

Thanks and godspeed!

**Comment by mitar** [comment]
Have you forgotten to add `reactive-var` package to the server side?

**Comment by DanielDornhardt** [comment]
Hey @mitar, sorry, yeah, it was my mistake, I was using a package and missing the import

```
import { ReactiveVar } from 'meteor/reactive-var'
```

or adding the package to my package. I forgot I was in a package, basically... Thanks and sorry for bothering you!

**Comment by adammoisa** [comment]
How do you add a package to server side? I wrote `import { ReactiveVar } from 'meteor/reactive-var'` at the top of my pub and I have ReactiveVar on client... still getting same error.

**Comment by mitar** [comment]
You should just add the package to your app or another package. It should be available automatically on client and server.

**Comment by rclai** [comment]
This is odd but, I'm having the same problem, but the best part is that I have `reactive-var` in my `packages` file. I'm on Meteor 1.8.1.

**Comment by rub1e** [comment]
@rclai - same - can't figure out what's going on here

Did you manage to solve this issue in the end?

**Comment by thebarty** [comment]
Just came here after adding this package to a meteor 1.10 project.

```
W20200407-11:35:03.829(2)? (STDERR) ReferenceError: ReactiveVar is not defined
W20200407-11:35:03.829(2)? (STDERR)     at _fn (packages/peerlibrary_reactive-publish.js:421:5)
W20200407-11:35:03.830(2)? (STDERR)     at packages/peerlibrary_reactive-publish.js:1501:3
W20200407-11:35:03.830(2)? (STDERR)     at packages/peerlibrary_reactive-publish.js:1506:4
```

I tried adding `meteor add reactive-var` and still get the message

Any ideas what else to try?

**Comment by thebarty** [comment]
related to https://github.com/peerlibrary/meteor-reactive-publish/issues/44

**Comment by thebarty** [comment]
this fixed it for me: `meteor add peerlibrary:reactive-publish@0.10.0` (some other coffeescript-based packages might need replacement for this to run. I had problems with practicalmeteor:mocha)

**Comment by mitar** [comment]
Yes, some other packages can force an older version of coffeescript which then forces an older version of this package, which then does not work with latest Meteor.

**Comment by darksipu** [comment]
Got the same issue on meteor 2.2.1 

Using `meteor add peerlibrary:reactive-publish@0.10.0` does not work.

Any idea what to do?

**Comment by mitar** [comment]
Could you make a small reproduction project/repository? I think it is some bad interaction between different packages. So can you pinpoint which packages badly interact, from those you are using?
