### ISSUE TITLE
server transform for cursors in autorun 

### ISSUE THREAD

**Issue by hoolymama** [peerlibrary/meteor-reactive-publish#22]
Hi,

I was wondering if its possible to add a field to the result in the cursor in an autorun?

I tried with [this package](https://github.com/maximummeteor/server-transform/) like so:

```
Meteor.publishTransformed("remarks", function () {
    this.autorun(function (computation) {
    return Remarks.find({}).serverTransform({extra: "hello"})
    })
})
```

The extra field is added when the query is not in the autorun function, but fails quietly if its in autorun. (autorun still works)

Its not very important because I can always do the extra work on the client. Just curious.

**Comment by mitar** [comment]
That package uses server-side autorun internally. So the author seems to be familiar with it. I would suggest you open an issue in that package.

**Comment by mitar** [comment]
I have this package for some similar features: https://github.com/peerlibrary/meteor-middleware

**Comment by hoolymama** [comment]
Thanks! meteor-middleware looks interesting - "post-process documents send to the subscriber" - I'll try that later.
