### ISSUE TITLE
Propagate errors inside autoruns to the outside publish function

### ISSUE THREAD

**Issue by mitar** [peerlibrary/meteor-reactive-publish#26]
If computation throws an exception in later reruns, we should catch that and propagate it to the outside publish function which should throw an error and stop. For example, if some permission checks are done inside an autorun, and they fail, that should propagate out.

In general it seems no exception handling is done inside autorun. This is OK for the first run, but not for later.

**Comment by emaciel10** [comment]
@mitar would this fix for this issue just be wrapping this `runFunc.call` in a try catch?

```
handle = Tracker.autorun (computation) ->
        result = runFunc.call publish, computation
```

I noticed while testing something out locally that any exceptions thrown on later autoruns don't clean up the client minimongo collections properly.

**Comment by etyp** [comment]
@mitar same with this - been testing #41 and #42 in our beta environment and it's working well.
