### ISSUE TITLE
Question: How to publish to specific client side collection?

### ISSUE THREAD

**Issue by DeanKamali** [peerlibrary/meteor-reactive-publish#39]
Hi everyone, 

wondering if it is possible to specify client side collection data will be published too? 

Example: publish only users with role: admin from ```Meteor.users``` collection to client side collection called ```admins```? is that possible?

**Comment by DeanKamali** [comment]
I managed it to figure it out 👍 

on client I have client side collection ```admins``` aka (virtual collection);

```const admin = new Mongo.Collection('admins');```

on server
```
Meteor.publish('providers', function () {
  let self = this;
  this.autorun((computation) => {
    return Meteor.users.find({ roles: 'admin' }).forEach((doc) => {
      // do something here with doc if you need to
      self.added("admins", doc._id, doc);
    });
  });
});
```

**Comment by mitar** [comment]
You might also want to use this package: https://github.com/peerlibrary/meteor-subscription-scope
