### ISSUE TITLE
Subscriptions never complete

### ISSUE THREAD

**Issue by dpatte** [peerlibrary/meteor-reactive-publish#4]
I am running meteor 1.2.
I have several publications which work well, but are not reactive.

Adding your package, with no other changes, has no effect (positive or negative) since I am not using autorun in my publications. My publications still work well, but not reactively

but once I modify my publications as follows
this.autorun() {
  /\* my old publication code */
}
The subscriptions never complete. My app sits with an idle indicator when I log in.

Also, in your documentation - what is the purpose of 'computation' that you pass as a parameter to autorun?

**Comment by mitar** [comment]
You will have to provide some reproduction, sorry. It works for me. Make a sample app which shows the problem you are mentioning.

> Also, in your documentation - what is the purpose of 'computation' that you pass as a parameter to autorun?

Nothing. This is what [Meteor passes to autorun function](http://docs.meteor.com/#/full/template_autorun). I am just explicit in all arguments you are getting so that you know what is available. It is the current computation.

**Comment by mitar** [comment]
Ping? What is with this?

**Comment by dpatte** [comment]
Still no luck on the Meteor 1.2 branch. Since there is critical development, I'm working on my 1.1 branch which works with lepozepo. I'll try debugging 1.2 shortly and see what I can find out. Thanks. I'll let you know.

**Comment by mitar** [comment]
Can you make a reproduction?

**Comment by mitar** [comment]
No feedback. Closing.

**Comment by dpatte** [comment]
Just in summary, I have now migrated to meteor 1.2. I am now using your reactive-publish library, and my publications work fine if I don't wrap the internals in a this.autorun(function() { });

But when I do wrap the internals of my publication functions in this.autorun, the publications never complete.

Note that none of my individual publication functions return multiple cursors from a single collection, but I do have a pair of publications that each return a single cursor from the same collection, which I expect meteor to merge at the client.

**Comment by mitar** [comment]
> Note that none of my individual publication functions return multiple cursors from a single collection, but I do have a pair of publications that each return a single cursor from the same collection, which I expect meteor to merge at the client.

That should not be a problem.

Can you please create a reproduction? It is really hard to debug this otherwise.

Are you using any other package which might interfere with publish (like monkey patching it)?

**Comment by dpatte** [comment]
Thanks for the help:

I have simplified things here, but part of my publish functions looks like this

```
Meteor.publish("usersAllFields", function()
{
 this.autorun(function (computation) {
  if (!this.userId)
    return [];
  if (isAdmin(this.userId))
    return Meteor.users.find(); // all users, all fields
  return Meteor.users.find({_id: this.userId}); // self only, all fields
 });
});

Meteor.publish("usersLimitedFields", function()
{
 this.autorun(function (computation) {
  if (!this.userId)
    return [];
  if (isAdmin(this.userId))
    return []; // already loaded above
  return Meteor.users.find({
    _id: {$ne: this.userId}, // ensure self not loaded again
    _id: {$in: findShared(this.userId)}, // shared users only
  }, {fields:{profile:1,emails:1}} ); // limited fields only
 });
});
```

And my subscription, 

```
doSubscribe = function()
{ 
    return Meteor.user()
    && Meteor.subscribe('usersAllFields') 
    && Meteor.subscribe('usersLimitedFields')
 }
```

findShared() is a function that returns an array of user_ids

My Iron:router setup looks like this

```
Router.configure(
{
  layoutTemplate: 'layout', // default template
  loadingTemplate: 'loading',   // template when loading
  notFoundTemplate: 'notFound', // template when 404 (not found)
  waitOn: doSubscribe
});
```

**Comment by mitar** [comment]
Can you make a reproduction? A repository with only the example code which shows how subscription never ends?

**Comment by dpatte** [comment]
Thanks. I can try. But it will take me a few days.

**Comment by mitar** [comment]
And how are you observing that it never finishes? If you subscribe from a web console, does it work then?

**Comment by dpatte** [comment]
I apologize. As mentioned, I recently moved to meteor 1.2.1 from meteor 1.1.0.3. I realize now that subscriptions are completing after all, but they don't have the data I expect.. In fact the only doc I seem to get is the user record for the current user. I should in fact be getting all the user records.  In the code above, I am using two publications - one to return a cursor to all the Users (I am admin) , and one where i return [] meaning no more Users. Is it still correct to return [] if I have no cursor to return from a publication?

**Comment by mitar** [comment]
Hm, not really. Because returning `[]` will I think not make it ready ever. You should do something like:

```
this.ready();
return
```

But maybe it even works, maybe there is some goody there to make it work. But this is now more a Meteor question than this package issue.

**Comment by dpatte** [comment]
OK. I tried this.ready(), and no difference. [] does work without this library though.

But since my prev. message, I have found a partial solution - at least it is better now, and I am getting data.
Within the computation I changed it to now using self., instead if this. Before the computation i do var self=this;

with this change my data comes through. but something is still odd. It is not fully reactive.

**Comment by dpatte** [comment]
So it seems like it is working. Some notes:
- [] works, since you can return an array of cursors, and it accepts an empty array; though I will try this.ready() again, since it is likely faster.
- 'this' inside the autorun doesn't seem to work, but predefining var self=this, and using self within the autorun does work. Your examples don't clearly show this.
- It does not seem work for me on Samsung note3's default browser - but this is more likely to be an issue with recent es6 support, not your module. It does work if I use firefox on the note3.

Thanks for your help, and questions. Its nice to have reactive publish working for me again. :)

**Comment by mitar** [comment]
You are right! `[]` should work from the code, I see now. And examples were really bad. This is because I converted them from CoffeeScript where `this` is bound to you automatically correctly. I fixed this now.

**Comment by mitar** [comment]
I made it so that `this` is automatically bound now to the publish.

**Comment by dpatte** [comment]
:) 

And I have resolved my problem with Samsung note3. It was an es6 issue - not an issue with your module at all.
