### ISSUE TITLE
Question: Meteor 1.8.1 - ReferenceError: ReactiveVar is not defined

### ISSUE THREAD

**Issue by DeanKamali** [peerlibrary/meteor-reactive-publish#44]
I'm seeing this error with Meteor 1.8.1, I do have reactive-var@1.0.11 installed with my project. 

```
W20190603-22:49:17.309(-4)? (STDERR) ReferenceError: ReactiveVar is not defined
W20190603-22:49:17.309(-4)? (STDERR)     at _fn (packages/peerlibrary_reactive-publish.js:421:5)
W20190603-22:49:17.309(-4)? (STDERR)     at packages/peerlibrary_reactive-publish.js:1501:3
W20190603-22:49:17.310(-4)? (STDERR)     at packages/peerlibrary_reactive-publish.js:1506:4
W20190603-22:49:17.310(-4)? (STDERR)     at packages/peerlibrary_reactive-publish.js:1512:3
W20190603-22:49:17.310(-4)? (STDERR)     at /Users/user/Projects/project/project/.meteor/local/build/programs/server/boot.js:419:36
W20190603-22:49:17.310(-4)? (STDERR)     at Array.forEach (<anonymous>)
W20190603-22:49:17.310(-4)? (STDERR)     at /Users/user/Projects/project/project/.meteor/local/build/programs/server/boot.js:228:19
W20190603-22:49:17.310(-4)? (STDERR)     at /Users/user/Projects/project/project/.meteor/local/build/programs/server/boot.js:479:5
W20190603-22:49:17.311(-4)? (STDERR)     at Function.run (/Users/user/Projects/project/project/.meteor/local/build/programs/server/profile.js:510:12)
W20190603-22:49:17.311(-4)? (STDERR)     at /Users/user/Projects/project/project/.meteor/local/build/programs/server/boot.js:478:11
=> Exited with code: 1
```

Any ideas?

**Comment by mitar** [comment]
I do not use it in code: https://github.com/peerlibrary/meteor-reactive-publish/blob/master/server.coffee

Which version of this package you have?

Can you check what is at line 421 at packages/peerlibrary_reactive-publish.js? Try to find that file inside Meteor bundle.

**Comment by jokel81** [comment]
Hi mitar

I have the same problem and i checked the js file you suggested.
I can see that the link is in the tests.coffee in line 25. 
Does this help?

Best regards
Jokel

**Comment by chungl** [comment]
I encountered the same issue today when installing this package into my project (also running 1.8.1). Mine failed at the same line as @DeanKamali , which appeared to be test code, consistent with @jokel81's observation that `ReactiveVar` is used in `tests.coffee`. Adding an import statement at the top of `tests.coffee` fixes this issue for me when I install my fork as a local package.

**Comment by mitar** [comment]
I think this was the issue about Meteor version incompatiblity with a package published with an older Meteor version. I republished the package with 1.8.1 and I think this should now be fixed. Try `peerlibrary:reactive-publish@0.9.0.`.
