### ISSUE TITLE
Update peerlibrary:reactive-mongo dependency to @0.3.0

### ISSUE THREAD

**Issue by wildhart** [peerlibrary/meteor-reactive-publish#45]
The current default reactive-mongo@0.2.2 doesn't let findOne use Oplog even with explicit `sort` and `ordered: false` parameters.

reactive-mongo@0.3.0 enables this feature.

**Comment by mitar** [comment]
Shouldn't those packages be already compatible? Is bumpy really necessary?

**Comment by mitar** [comment]
But PR welcome.

**Comment by wildhart** [comment]
I've tried switching back and forth between reactive-mongo@0.2.2 and 0.3.0 and with 0.2.2 findOne doesn't use oplog, but 0.3.0 it does. Every time.  See [forum post](https://forums.meteor.com/t/oplog-support-with-findone/49163/5).

There is a repro [here](https://github.com/zodern/reactive-publish-repro).

The most recent [reactive-mongo PR #4](https://github.com/peerlibrary/meteor-reactive-mongo/pull/4) forced `ordered` to default to `true` when `sort` is specified, which then bypasses the oplog.  Before that the `ordered` flag didn't exist but the default behaviour was ordered.

Will do a quick PR...
