### ISSUE TITLE
this.unblock not working (is this intended?)

### ISSUE THREAD

**Issue by Aur0r** [peerlibrary/meteor-reactive-publish#8]
Hi all,

I noticed that with this library I get an error when using this.unblock() in a publish method:

stack: 'TypeError: Object [object Object] has no method \'unblock\'\n    at [object Object].<anonymous> (app/packages/issuebrowser/
server/index.js:138:8)\n    at [object Object].<anonymous> (packages/peerlibrary_reactive-publish/packages/peerlibrary_reactive-publish.js:310:1

Any workaround that one can still use this.unblock? Or is there a problem with allowing it with this plugin?

Best regards

**Comment by mitar** [comment]
Publish functions do not have `unblock`. Only Meteor methods have them.

Or, are you using some 3rd party package which provides `unblock` inside publish?
